### ISSUE TITLE
Drag & drop stops working on Firefox 45

### ISSUE THREAD

**Issue by mincem** [gmail-manager-community/gmail-manager-community#29] opened 2016-03-13 00:59 UTC
Since Firefox updated to 45, all drag and drop stops working everywhere on the browser when Gmail Manager connects to the account. Drag and drop works fine for a few seconds until the unread counter shows a number, and then it doesn't work anymore. This problem affects dragging tabs, bookmarks and selected text/images from websites.

**Comment by skrivskithar** [comment] 2016-03-19 15:28
ahhh so this was it! I was trying to find the culprit when I started suspecting GM since it seems to happen after the new emails popups disappear. Upon further testing I'm almost sure it only happens if you drag WHILE a notification is poping up (snipplets), since I waited for them to close upon browser startup (alway have unread emails) and I still CAN drag.

EDIT: well I was wrong, it eventually stopped worked. Rolled back to FF44.0.2 for now.

**Comment by gmng** [comment] 2016-04-01 12:20
You also cannot drag and drop your bookmarks / bookmark toolbar when you try to customize it in FF45. If you disable GM, everything works as it should. Any news on this bug fix?

**Comment by Endor8** [comment] 2016-04-03 14:34
I can confirm this totally. With gmail-manager-community activated all drag and drop stops working everywhere on the browser since Firefox 45. This should be fixed as soon as possible.

**Comment by M3Rocket** [comment] 2016-04-06 04:12
I also ran into this problem and I thought it was another extension causing this. But I can confirm everything works as normal once Gmail Manager NG is disabled. Hopefully an easy fix since there is nothing I know of that works as well as this extension for people with multiple Gmail accounts like myself.

**Comment by ath0mas** [comment] 2016-04-26 22:31
Still facing same problem with Drag'n Drop in released Firefox 46? Not linked to another addon?
In my case, yet with FF45, things work fine, and I did not faced any issue with DnD of tabs, bookmarks (Win7/10)

**Comment by mincem** [comment] 2016-04-27 02:25
After reading your comment, I went and checked on Firefox updates, FF46 was available, I upgraded, and reactivated Gmail Manager. Seems it's been working fine for a couple of hours now.

**Comment by M3Rocket** [comment] 2016-04-27 03:38
It still doesn't work for me with FF 46. When you first start the browser, drag and drop works. But as soon as Gmail Manager logs into your email accounts, drag and drop of tabs fail to work again. Reverting to ff 44.0.2.

**Comment by M3Rocket** [comment] 2016-04-27 07:52
I did some more testing and I think it has to do with the snippets window. If I disable displaying the snippets window on all accounts when new mail is received, then drag and drop will work. If the snippet window is being displayed, the drag and drop works. As soon as the new mail snippet window disappears, drag and drop no longer works.

I then tested by disabling new mail snippets window, then right clicking and manually selecting "Display  Mail Snippets..." And can confirm that as soon as that window pops up, then disappear when all mail snippets are displayed, drag and drop stops working till the browser is reset.

BTW--I've tested this on two different computers with different versions of FF.

**Comment by mincem** [comment] 2016-04-27 15:58
Seconded. It was working fine while I had no new mail, but as soon as I got a snippet, drag & drop stopped again. Also, Firefox stopped exiting properly (as reported in #28).

Using Gmail Manager with snippets disabled seems to avoid both issues, so far.

**Comment by seaders** [comment] 2016-05-04 22:40
If this happens to you, check if the popup animation has stalled for you (if you had that enabled).  I experienced the same behaviour, but found these things were disabled for me while the popup notifier was still on screen.  At some stage, during one of the upgrades, I found the popup notifier would still popup, but not fully animate away.  It would stay on screen, still showing a bit of the header.

If I manually close that guy, I get all the drag & drop functionality I was missing back.

**Comment by M3Rocket** [comment] 2016-05-04 23:23
I agree that this has definitely something to do with the snippet window not closing properly. 

I can manually trigger the snippets window with a right click and selecting "Display Mail Snippets..." When the mail snippets window is showing, I can click the "X" to close the window, and that allows drag and drop to continue working. But if I wait for the snippets window to close by itself, drag and drop stops working even after the snippet window is gone from the screen.

**Comment by seaders** [comment] 2016-05-05 00:27
I've just poked around with this locally and opened a PR, https://github.com/gmail-manager-community/gmail-manager-community/pull/31 which fixes it.

Basically at some point, the window stops animating off screen, but the internal check checks the windows height before deciding to close it.  If that misreports, or stops moving, it stays forever, creating this situation forever.

If you could take a look @ath0mas I've got this working locally and it's sorted the problem out.

**Comment by M3Rocket** [comment] 2016-05-05 05:35
Nice work @seaders! I tried out your changes from your Pull Request and it does fix this problem completely on my setups as well! I now have snippets again. Woo-hoo! 

I recommend @ath0mas to approve the merge request.

**Comment by ath0mas** [comment] 2016-05-05 06:18
Nice!
I should have time to do a quick review and merge later today or tomorrow maximum 😉

**Comment by ath0mas** [comment] 2016-05-06 01:43
May some of you test that recent changes (merged PR #31 and next commit) does fix the problem? please
(I would prefer not to have to make a "beta" built XPI at the moment)

and if you faced **#28 process not exiting properly** too, please check it at the same time and report

**Comment by ath0mas** [comment] 2016-05-06 14:08
**[0.7.1](https://github.com/gmail-manager-community/gmail-manager-community/releases/tag/0.7.1)** released ; _"soon"_ on **AMO**

**Closed as completed by ath0mas** 2016-05-06 14:08 UTC
Labels: bug

**Comment by seaders** [comment] 2016-05-06 14:31
(any chance of a mention in the credits?  I do a bit of contracting, and having the name in OS projects does help out)

**Comment by ath0mas** [comment] 2016-05-06 14:52
My bad!
I got interrupted while writing the release notes and forgot last issue's participants were missing...
You all are mentioned in the Credits part of this 0.7.1 release now :wink: Thx again

**Comment by seaders** [comment] 2016-05-06 14:53
Not at all dude, thank you for maintaining it.  I'll try help out with some of the other issues you've requested help on.  I've been using this plugin for years, but finally have some spare time to help out with it.

**Comment by M3Rocket** [comment] 2016-05-07 07:29
Just FYI @ath0mas, the new code in 0.7.1 makes the snippet window "jumpy." Instead of smoothly animating up and down, it simply appears, moves up a few steps. When it's done showing snippets, it moves down a few lines then disappears. 

I much prefer the window to move up completely and move down completely like the old code.

**Comment by skrivskithar** [comment] 2016-05-14 13:05
sorry to bump, but I noticed that every now and then (actually, quite infrequently), drag and drop does STILL stop working. It's not that constant to call it an issue per se, but still... I think that when it happens, it happens at startup when the snippets window popups up (as most of my email accounts always have unread emails)

edit: it definitely happens every once in a while and specially not on startup, but after a while. Still probably related to snippets.
