### ISSUE TITLE
Firefox not exiting properly since Firefox 45/Linux

### ISSUE THREAD

**Issue by StephenAtty** [gmail-manager-community/gmail-manager-community#28] opened 2016-03-12 16:10 UTC
Since upgrading to Firefox 45 on Linux I keep finding that when I exit FF the application doesn't actually terminate properly. If I disable the gmail extension then it behaves correctly.

**Comment by Em-En** [comment] 2016-04-20 07:32
Same here. 
Firefox 45.0.2
Windows 7 64 SP1

**Comment by ath0mas** [comment] 2016-04-26 22:34
Can you give more details? and same problem with released Firefox 46?
In my case I don't see any ghost process for Firefox after closing it (Win7/10)

**Comment by StephenAtty** [comment] 2016-04-27 06:36
It seems to have started behaving itself again on Linux

**Comment by Em-En** [comment] 2016-04-28 19:50
I'll try to be more specific, but not sooner than on wednesday. Here is some background: I disabled gmail-manager when I realized that everything looks like it is the add-on which makes Firefox process stay when the program is supposed to quit working. In order to verify that I disabled all the add-ons and then enabled one-by-one.
On the other hand I've got another computer with W7 32, Firefox 45.0.2, similar set of add-ons (including gmail-manager) and never had any problem with this one.

**Comment by Em-En** [comment] 2016-05-04 13:55
I have just confirmed it again on that Windows 7 64, Firefox 45.0.2 machine. Just after re-enabling gmail-manager Firefox process stayed in memory.
After upgrading to 46.0.1 (I had to force it, because this release isn't offered on auto-update yet) it seems to work and, what is more important, quit properly.

**Comment by ath0mas** [comment] 2016-05-06 01:53
Infinite loop in snippets alert window close was detected while fixing #29
I don't have a built "beta" XPI for you, but if you know how to test from recent commits, it would be great to report ;)

**Comment by Em-En** [comment] 2016-05-06 10:16
Well, frankly speaking it's my work computer and it is working properly now... I'm afraid that I won't be able to perform any tests.

**Comment by ath0mas** [comment] 2016-05-06 14:08
**[0.7.1](https://github.com/gmail-manager-community/gmail-manager-community/releases/tag/0.7.1)** released ; _"soon"_ on **AMO**

**Closed as completed by ath0mas** 2016-05-06 14:08 UTC
Labels: bug
